### ISSUE TITLE
A RISCV assembler and its documentation

### ISSUE THREAD

**Issue by jacob-navia** [riscv/learn#10]
### Resource Title

Tiny-asm

### Resource Description

Tiny-asm is a standard C RISCV assembler derived from GNU gas. It is very small and easy to compile and install, since it consists of only 2 files: asm.c and asm.h. It is in
https://github.com/jacob-navia/tiny-asm.git
This repository includes the documentation.

### Resource Link

https://github.com/jacob-navia/tiny-asm.git

### Required Background (Optional)

If you want to tinker with the assembler you have to know the C language.
The documentation is in English
Yoiu can compile the assembler in any machine that supports standard C.

### Additional Details (Optional)

For more information, donations, whatever:
jacob@jacob.remcomp.fr

**Comment by rpsene** [comment]
@jacob-navia, thanks for your suggestion! We aim to include courses and materials that offer a comprehensive and mature learning experience from start to finish. At this moment, we're not able to include your contribution, but this doesn't diminish the value of your suggestion. Please know that your contribution is always welcome, and we encourage you to revisit and reopen your suggestion whenever you feel it meets the criteria for a mature, end-to-end learning experience.
