### ISSUE TITLE
[New RISC-V Tutorial Resource] - CREATOR: didaCtic and geneRic assEmbly progrAmming simulaTOR

### ISSUE THREAD

**Issue by dcamarmas** [riscv/learn#11]
### Resource Title

CREATOR

### Resource Description

CREATOR is a didactic simulator that allows the development, simulation, and debugging of RISC-V (RV32IMFD) assembly programs intuitively and interactively. It is a web application, so it can be used on any type of device (desktop, tablet, smartphone, etc.) without installing additional software, only a modern web browser (Google Chrome, Mozilla Firefox, Apple Safari, etc.) is required.

For more information: https://creatorsim.github.io/

### Resource Link

https://creatorsim.github.io/creator/

### Required Background (Optional)

- Programming basics (loops, conditionals, functions, etc.)

### Additional Details (Optional)

We have seen issue #9 , if a new category of visual tools is added, CREATOR we believe fits in this category. Otherwise, we believe that it fits in the section "Intermediate-Level resources"

**Comment by KuthumiPepple** [comment]
Thanks for you submission. I will add the new category for software and tools soon.
