### ISSUE TITLE
[New RISC-V Tutorial Resource] - Learn with SHAKTI

### ISSUE THREAD

**Issue by govardhnn** [riscv/learn#14]
### Resource Title

Learn with SHAKTI

### Resource Description

SHAKTI is an open-source initiative by the Reconfigurable Intelligent Systems Engineering (RISE) group at IIT-Madras. 
This Tutorial Resource guides one to writing RISC-V assembly and C Programs and implement them on Spike, RISC-V GDB and OpenOCD tools. There are Assignments and Sample Programs to get started with.

### Resource Link

https://shakti.org.in/learn_with_shakti/intro.html

### Required Background (Optional)

Basic exposure to RISC-V ASM and C Programming

**Comment by KuthumiPepple** [comment]
Thanks for your submission. Based on the required background for this resource, I think it would be better suited somewhere in the `Intermediate-level` section. If you have a different idea, please let me know.

**Comment by govardhnn** [comment]
Yes, I would also like to link the [Shakti RISC-V ASM Manual](https://shakti.org.in/docs/risc-v-asm-manual.pdf) in the description as it has more example programs, best suited to the scope `Intermediate-level`. 
Can I submit a PR to make things easy?

**Comment by KuthumiPepple** [comment]
Sure, go ahead and submit a PR

**Comment by govardhnn** [comment]
I have added [PR-18](https://github.com/riscv/learn/pull/18) to include this resource.
I am also curious if you would like my contributions on a few more areas I think are needed here:
 - Port the README from md -> adoc
 - Split the README according to their category and hyperlink them all
 - Remove Date Added
 - Purge notes.txt

**Comment by KuthumiPepple** [comment]
You can remove notes.txt, it's no longer useful. I addressed the 'date added' column in the review of your changes. Porting README to adoc and splitting the README by categories are good improvement ideas. I have put it to the admin, I am awaiting his response.

**Comment by KuthumiPepple** [comment]
He agrees with the proposed changes, please go ahead

**Comment by govardhnn** [comment]
Sure, will create a new PR for it. Thank you
