### ISSUE TITLE
[New RISC-V Tutorial Resource] - Advanced Computer Architecture-RISC-V Edition

### ISSUE THREAD

**Issue by Shreesh-Kulkarni** [riscv/learn#2]
### Resource Title

Computer Architecture- A Quantitative Approach-6th Edition, by David A. Patterson and John L. Hennessey

### Resource Description

Covers advanced computer architecture concepts pertaining to high performance computing principles and domain specific architectures along with examples and exercises pertaining to the RISC-V ISA-(6th Edition onwards). This is a step-up from the first book,(Hardware-Software Interface), with advanced concepts like Instruction , Data and Thread Level Parallelism along with introduction to Vector, SIMD and GPU architectures.
It also continues the tradition of using real-world examples to demonstrate the concepts, by introducing memory organizations and architectures of ARM Cortex A8, Intel Core i7, Nvidia GTX-280 GPUs and so on.

### Resource Link

[Amazon Book Link](https://a.co/d/fuvp97D)

### Required Background (Optional)

Prerequisites : Digital Design, Basic Computer Architecture Concepts, and introductory knowledge on the RISC-V ISA.
The reader is recommended to finish the Computer Organization and Design -Hardware Software Interface-RISC-V edition first, before moving forward with this book.

### Additional Details (Optional)

This book is generally preferred for Master Students, so I would suggest to keep this resource in the Advanced resource section after the Intermediate stage. This book could still be included in the intermediate section, but the Hardware Software Interface is a necessary prerequisite to have a clear understanding of the concepts.

**Comment by KuthumiPepple** [comment]
Thanks for your contribution. I agree that including this in a new advanced category makes sense. I also think adding a prerequisite column to the tables would be very useful.

**Comment by Shreesh-Kulkarni** [comment]
Thanks. If you don't mind, I can submit a PR to introduce these changes in the README file of the repository.

**Comment by KuthumiPepple** [comment]
Sure go ahead. You could create a new table for advanced resources and add it there. Later I think we will update the tables in the learning pathway to include a column for prerequisites.

**Comment by KuthumiPepple** [comment]
Hi Shreesh, you could simply add this resource as an entry to the Intermediate-level resources for now.

**Comment by Shreesh-Kulkarni** [comment]
I have added the resource in the intermediate section as suggested. I have created a Pull Request for the same.
