### ISSUE TITLE
[New RISC-V Tutorial Resource] - RVV intrinsics viewer

### ISSUE THREAD

**Issue by camel-cdr** [riscv/learn#3]
### Resource Title

RVV intrinsics viewer

### Resource Description

A third party documentation website for the vector extension intrinsics, currently including pretty much all intrinsics variations, and fuzzy search.

### Resource Link

https://dzaima.github.io/intrinsics-viewer/

**Comment by KuthumiPepple** [comment]
In the resources list, this should directly follow "RISC-V vector extension demystified" right?

**Comment by camel-cdr** [comment]
Yes, I'd put both in Intermediate, but "For those with some background in digital logic design" doesn't really fit, as this are more resources for software development.

I think there should be a place for categorized resources and separate, more curated learning tacks.

**Comment by KuthumiPepple** [comment]
Having a place for categorized resources makes sense. If I may ask, suppose I create a place for categorized resources, what other categories other than "software development resources" could go in there?

**Comment by camel-cdr** [comment]
Maybe something like "software development tutorials"?

**Comment by KuthumiPepple** [comment]
Let's say, suppose the learning resources are broadly grouped into two: 
- `Learning pathway/track` (group 1)
- `Categorized resources` (group 2) 

The `Learning pathway/track` would contain curated contents for beginner-level, intermediate-level and possibly advanced-level learners. Meanwhile, within the `Categorized resources`, we could have different collections of learning resources or helpful aids, for example, "software development" could be one such collection which will contain resources related to software development like the ones you shared. My question was more like, based on your experience and knowledge of resources out there, there would be more collections we could add into the `Categorized resources` group right? I just want to make sure that such a system of classification would work as the `Learning pathway/track` would not be a good fit for all risc-v learning resources submitted by the community.

**Comment by KuthumiPepple** [comment]
I created a new "Softwares and Tools" resource category and I will add this there. If you have a different view, please comment here.
