### ISSUE TITLE
[New RISC-V Tutorial Resource] - Introduction to RISC-V Assembly (video series in Portuguese)

### ISSUE THREAD

**Issue by gboncoffee** [riscv/learn#35]
### Resource Title

Introdução à Assembly de RISC-V

### Resource Description

It's a series of YouTube videos, in Portuguese, produced as material for the Teaching Assistant program of the CI1210 ("Projetos Digitais e Microprocessadores", free-translated to "Digital Projects and Microprocessors") classes of the Computer Science degree at the Universidade Federal do Paraná (Federal University of Paraná), Brazil. It encompasses the basic RISC-V IM architecture and uses the [EGG](https://github.com/gboncoffee/egg) emulator.

The series is not yet complete, the production is ongoing.

### Resource Link

https://youtube.com/playlist?list=PLFe3Zrf4uj4vlRF21jK3vzfCuSSJ5I_uB&si=bx4eHYpPLBxAUTy8

### Required Background (Optional)

Basic C programming and digital logic understanding is desired.

**Comment by thong-phn** [comment]
Thanks for your contribution @gboncoffee 🎉
Currently, we understand that the production is ongoing so we will let this issue open for a while until your series is finshed.

**Comment by gboncoffee** [comment]
Hello, the production is finished by now.

**Comment by gboncoffee** [comment]
Thanks! ;)
