### ISSUE TITLE
[New RISC-V Tutorial Resource] - Implementing a Linker from Scratch

### ISSUE THREAD

**Issue by ksco** [riscv/learn#39]
### Resource Title

Implementing a Linker from Scratch

### Resource Description

This is an open course launched by PLCT Lab. In this course, we use Go to implement an RV64GC (RISC-V 64-bit) architecture linker from scratch, which can correctly link relatively simple C programs. By studying this course, one should be able to have a solid understanding of how the core parts of a static linker work.

### Resource Link

https://github.com/ksco/rvld

### Required Background (Optional)

1. Familiar with the Go programming language.
2. Have a basic understanding of the RISC-V instruction set.
3. Have a basic understanding of the compilation process.
4. The code repository is English-friendly, course videos and materials are only available in Chinese.

### Additional Details (Optional)

This is an intermediate-level course.

**Comment by bayareaunicorn** [comment]
Thanks for sharing
