### ISSUE TITLE
[New RISC-V Tutorial Resource] - Teaching experiences with RVfpga

### ISSUE THREAD

**Issue by danidep02** [riscv/learn#45]
### Resource Title

Teaching experiences with RVfpga

### Resource Description

In the GitHub repository [RVfpga-sim-addons](https://github.com/artecs-group/RVfpga-sim-addons), we demonstrate how we adapted and utilized the [RVfpga: Understanding Computer Architecture](https://university.imgtec.com/rvfpga-el2-v3-0-english-downloads-page/) and the [RVfpga-SoC](https://university.imgtec.com/rvfpgasoc-download-page-en/) packages provided by Imagination Technologies, as well as the [Ripes](https://github.com/mortbopet/Ripes) simulator, in the labs of the two following courses instructed at the Complutense University of Madrid (UCM)

- Computer Organization: Second-year course in the Computer Science Engineering degree program at UCM.
- Integrated Systems Architecture: Fourth-year course in the Electronics and Communication Engineering degree program at UCM. 

### Resource Link

https://github.com/artecs-group/RVfpga-sim-addons

### Required Background (Optional)

Prerequisite knowledge required in each of the courses: 
- Computer Organization: Basic understanding of programming fundamentals and digital logic design. A foundational course in Computer Architecture or related topics is highly recommended.
- Integrated Systems Architecture: Solid foundation in Computer Organization and Architecture, as well as Hardware Description Languages (HDL). Prior coursework in these areas is essential for success in this class.

**Comment by rpsene** [comment]
@danidep02  I will integrate it shortly!

**Comment by danidep02** [comment]
Great!
Thanks

**Comment by danidep02** [comment]
Hi Rafael, 
Are there any news in the integration of the new materials? 
Thanks
Best regards

**Comment by rpsene** [comment]
done, @danidep02 !

**Comment by danidep02** [comment]
Great, thanks!
