### ISSUE TITLE
[New RISC-V Tutorial Resource] - HaDes-V course

### ISSUE THREAD

**Issue by tscheipel** [riscv/learn#53]
### Resource Title

Microcontroller Design, Lab: HaDes-V

### Resource Description

The [Instruction Guide](https://doi.org/10.3217/nytm4-grv34) and this source code template for the [Microcontroller Design, Lab](https://online.tugraz.at/tug_online/wbLv.wbShowLVDetail?pStpSpNr=525082) is an Open Educational Resource (OER) developed by [Tobias Scheipel](https://www.scheipel.com/), David Beikircher, and Florian Riedl, Embedded Architectures & Systems Group at Graz University of Technology. It is designed for teaching and learning microcontroller design and hardware description languages, using the HaDes-V architecture, a RISC-V-based processor.

### Resource Link

https://github.com/tscheipel/HaDes-V/

### Additional Details (Optional)

all details can be found in the Instruction Guide and the GitHub template README.

**Comment by rpsene** [comment]
Added! https://github.com/riscv/learn/commit/fddf6fa2daf7ca981a953025042b10c3a26eeef0

Thanks for contributing, @tscheipel.

**Comment by tscheipel** [comment]
Thanks. I think it would fit the Intermediate learning materials better though, @rpsene .

Best, Tobias.

**Comment by rpsene** [comment]
done! @tscheipel
