### ISSUE TITLE
[New RISC-V Tutorial Resource] - Hands-on course on designing RV32I Processor

### ISSUE THREAD

**Issue by raulbehl** [riscv/learn#6]
### Resource Title

Hands-on RISC-V Processor Design

### Resource Description

This tutorial offers a deep dive into the world of computer architecture and processor design, with a specific focus on the RISC-V Instruction Set Architecture (ISA). The course covers the following:

- Fundamental concepts of computer architecture and processor design
- Practical exposure to the unprivileged RISC-V Instruction Set Architecture (ISA)
- Learn to design a single-cycle RV32I compliant processor from scratch in SystemVerilog
- Create RISC-V assembly programs and execute them on the designed processor

### Resource Link

https://quicksilicon.in/course/riscv

### Required Background (Optional)

Some exposure to using SystemVerilog for Design is recommended but not necessary

**Comment by algorhtym** [comment]
Thank you for your contribution. This resource has now been added to the resources.
