### ISSUE TITLE
[Request] - RISC-V Visual Tools

### ISSUE THREAD

**Issue by ajithpv** [riscv/learn#9]
### Contact Details

Ajith P V, ajithpv@outlook.com

### Request Details

It would be better to add one more section for some of the best visual tools that helps to understand the RISC-V in a better way.
These tools can be used during the beginner or intermediate tutorials to get the visualization of the RISC-V ISA.

Example:
1. [emulsiV](https://eseo-tech.github.io/emulsiV/):
emulsiV is a visual simulator for a simple RISC processor called Virgule.
Virgule is a 32-bit RISC processor core that implements a minimal subset of the RISC-V instruction set. Here, “minimal” means that Virgule accepts only the instructions that a C compiler would generate from a pure stand-alone C program. 

1. [RISC-V Instruction Encoder/Decoder](https://luplab.gitlab.io/rvcodecjs/):
This tool is an online encoder/decoder for RISC-V instructions. Users can input RISC-V instructions in their assembly or binary format and get the full conversion from one to the other.

**Comment by KuthumiPepple** [comment]
Thanks for your submission. A section for visualization tools sounds good. I'll add that and request for a review from you.
